title: SSH
description: 个人博客

disqus_shortname: shortname
# Assign a default image for your site's header and footer
default_bg: default_bg.jpg
search: true
share: true
fin_color: "255,255,255"
url: http://ssh.today

# Gems used
gems:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag

# Archives configuration
# https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

author:
  name: shenshaohui
  picture: wukong.jpg
  email: 443939294@qq.com
  description: "Talk is cheap, Show me the code."
  github: "shenshaohui1991"

links:
  - title: 首页
    url: /
    external: false
    icon: home
  - title: 分类
    url: /categories
  - title: 标签
    url: /tags

# Sitemap configuration
# https://github.com/kinnetica/jekyll-plugins
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"

timezone: Asia/Shanghai
future: true
markdown: kramdown
highlighter: rouge
paginate: 6
paginate_path: "/blog/:num/"

collections:
  posts:
    output: true
    permalink: /blog/:title
  pages:
    output: true
    permalink: /:title

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6